services:
  rdgen:
    build:
      context: .
      args:
        PIP_INDEX_URL: "${PIP_INDEX_URL:-https://pypi.org/simple}"
        PIP_TRUSTED_HOST: "${PIP_TRUSTED_HOST:-}"
    restart: unless-stopped
    environment:
      SECRET_KEY: "${SECRET_KEY}"
      GHUSER: "${GHUSER}"
      GHBEARER: "${GHBEARER}"
      GENURL: "${GENURL}"
      ZIP_PASSWORD: "${ZIP_PASSWORD}"
      GHBRANCH: "${GHBRANCH:-master}"
      PROTOCOL: "${PROTOCOL:-https}"
      REPONAME: "${REPONAME:-rdgen}"
      SH_SECRET: "${SH_SECRET:-}"
    ports:
      - "8000:8000"
    dns:
      - 8.8.8.8
    volumes:
      - ./exe:/opt/rdgen/exe
      - ./png:/opt/rdgen/png
      - ./temp_zips:/opt/rdgen/temp_zips
