# Generated by Django 6.0.6 on 2026-07-22 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0004_userentitlement_githubrun_delivery_quota'),
    ]

    operations = [
        migrations.AlterField(
            model_name='githubrun',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
