# Generated by Django 6.0.6 on 2026-07-22 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0005_alter_githubrun_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrun',
            name='quota_chargeable',
            field=models.BooleanField(default=False),
        ),
    ]
