# Generated by Django 6.0.6 on 2026-08-05 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rdgenerator', '0008_activationcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationEmailCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, max_length=254)),
                ('code_hash', models.CharField(editable=False, max_length=64)),
                ('request_ip', models.GenericIPAddressField(blank=True, db_index=True, null=True)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('consumed_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('invalidated_at', models.DateTimeField(blank=True, db_index=True, null=True)),
            ],
            options={
                'verbose_name': '注册邮箱验证码',
                'verbose_name_plural': '注册邮箱验证码',
                'ordering': ('-created_at', '-pk'),
                'indexes': [models.Index(fields=['email', 'created_at'], name='rdgen_reg_email_created_idx')],
            },
        ),
    ]
